version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mockapi_server
    ports:
      - "8000:8080"
    volumes:
      - ./writable:/var/www/html/writable
      - ./database:/var/www/html/database
    environment:
      - CI_ENVIRONMENT=production
      - database.default.database=/var/www/html/writable/database.db
    command: php spark serve --host=0.0.0.0 --port=8080
    restart: unless-stopped